// Generates src/skill-content.generated.ts from the canonical skill document
// at graphlint/skill.md (repository root: ../../graphlint/skill.md relative to
// integrations/dsh).  The YAML frontmatter is stripped; the resulting body is
// byte-identical to what the Python side derives (graphlint.agent_tools.skill_body).
//
// Run automatically before tsc via `npm run build`.

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const source = path.resolve(here, '../../../graphlint/skill.md')
const output = path.resolve(here, '../src/skill-content.generated.ts')

let text = await readFile(source, 'utf8')
if (text.startsWith('---')) {
  const end = text.indexOf('\n---', 3)
  if (end === -1) {
    throw new Error(`graphlint/skill.md: unterminated YAML frontmatter`)
  }
  text = text.slice(end + 4)
}

// Must match graphlint.agent_tools.skill_body(): strip surrounding whitespace,
// then append exactly one newline.
const body = text.trim() + '\n'

const header = [
  '// @generated by scripts/generate-skill.mjs — do not edit.',
  '// Source: ../../graphlint/skill.md (YAML frontmatter stripped).',
  '',
].join('\n')

await writeFile(output, header + `export const SKILL_BODY: string = ${JSON.stringify(body)}\n`)

console.log(`[generate-skill] wrote ${path.relative(here, output)} (${body.length} chars)`)
